### PR TITLE
App Install Location

### PR DESCRIPTION
**Pull request by SweetLion**
The internal memory of my device is quite small, this PR should allow users to easily move the app to the microSD.

"To allow the system to install your application on the external storage, modify your manifest file to include the android:installLocation attribute in the element, with a value of either "preferExternal" or "auto"." (source: https://developer.android.com/guide/topics/data/install-location.html)

### CODE REVIEW

**Comment by javiersantos** [comment]
Thanks for your PR. Could you check if ML Manager is able to extract apps installed on the external storage?

**Comment by SweetLion** [comment]
Yes, I can check it on my device. Do you have the .apk for me?

**Comment by javiersantos** [comment]
Sure. Here you are: http://expirebox.com/download/be25f36e39908afab909f5b45092ada9.html (will expire in 24 hours). 

This APK is signed with another keystore and it isn't going to receive any future update. You should remove the actual ML Manager and install it.

Thanks.

**Comment by SweetLion** [comment]
Thanks Javier. It works well :)

**Pull request merged**
